In [ ]:
#in  pytorch everything is tensors , in tensors we have different dimentions


In [1]:
import torch

In [2]:
print(torch.__version__)

2.1.2+cpu


In [3]:
x = torch.empty(3)
x

tensor([5.1227e+02, 1.2191e-42, 0.0000e+00])

In [4]:
x = torch.empty(2,3) #2d
x

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
x = torch.empty(2,2,3) #3d
x

tensor([[[[5.3201e+02, 1.2191e-42, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 0.0000e+00]],

         [[0.0000e+00, 0.0000e+00, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 0.0000e+00]]],


        [[[0.0000e+00, 0.0000e+00, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 0.0000e+00]],

         [[0.0000e+00, 0.0000e+00, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 0.0000e+00]]]])

In [8]:
x = torch.ones(2,2)  #prints ones
x

tensor([[1., 1.],
        [1., 1.]])

In [9]:
x = torch.tensor([2.5,0.1])
x

tensor([2.5000, 0.1000])

In [10]:
x = torch.rand(2,2)
y = torch.rand(2,2)
print(x)
print(y)
z = x+y
z = torch.add(x,y)
print(z)

tensor([[0.6877, 0.9047],
        [0.2695, 0.6974]])
tensor([[0.1615, 0.0082],
        [0.0622, 0.5173]])
tensor([[0.8492, 0.9128],
        [0.3316, 1.2146]])


In [12]:
x = torch.rand(2,2)
y = torch.rand(2,2)
print(x)
print(y)
#pytorch every function that has a trailing underscore will do an in-place operation , so this will modify the variable that it applied
y.add_(x) #i=this will modify y  and add all of the elements of x to our y ,

print(y)  

tensor([[0.3533, 0.6784],
        [0.4708, 0.9202]])
tensor([[0.2940, 0.9405],
        [0.0210, 0.7403]])
tensor([[0.6472, 1.6190],
        [0.4918, 1.6604]])


In [15]:
x = torch.rand(4,4)
print(x)
y = x.view(16)
print(y)

tensor([[0.6449, 0.0374, 0.6890, 0.0914],
        [0.5701, 0.5781, 0.1847, 0.0363],
        [0.0608, 0.2287, 0.7235, 0.0514],
        [0.7744, 0.4963, 0.2481, 0.6050]])
tensor([0.6449, 0.0374, 0.6890, 0.0914, 0.5701, 0.5781, 0.1847, 0.0363, 0.0608,
        0.2287, 0.7235, 0.0514, 0.7744, 0.4963, 0.2481, 0.6050])


In [16]:
import torch
import numpy as np

#both objects share the same memory
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [17]:
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)

a.add_(1)  #rememebr all the underscore functions will modify our variable in place at one so if we add one to each element
print(a)
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [20]:
a = np.ones(5)
print(a)
b = torch.from_numpy(a)
print(b)

print("\n")

a+=1
print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [24]:
if torch.cuda.is_available():
    device=torch.device("cuda")
    x = torch.ones(5, device=device)
    y = torch.ones(5)
    y = y.to(device)
    z = x+y
    z.to("cpu")


In [25]:
x = torch.ones(5, requires_grad=True)
print(x)

tensor([1., 1., 1., 1., 1.], requires_grad=True)
